import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { supabase } from "../utils/supabase";

const channel = supabase.channel("user1-location", {
  configs: {
    broadcast: { ack: true },
  },
});

const max = 10;

const Home: NextPage = () => {
  const [self, setSelf] = useState(0);
  const [openent, setOpenent] = useState(0);

  function subscribe() {
    channel
      .on("broadcast", { event: "location" }, (payload) =>
        setOpenent(payload.payload.count)
      )
      .subscribe((status: string) => {
        if (status == "SUBSCRIBED") {
          console.log("Connected");
        }
      });
  }

  async function sendMessage() {
    if (openent < max && self < max) {
      updateSelf(self + 1);
    }
  }

  async function updateSelf(count: number) {
    setSelf(count);

    await channel.send({
      type: "broadcast",
      event: "location",
      payload: { count: count },
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={subscribe}>Connect</button>
        <div className={styles.divider}></div>
        <div>{`Maximum: ${max}`}</div>
        <div className={styles.divider}></div>
        <div>{`( Self: ${self} ) -----  ( Openent: ${openent} )`}</div>
        <div className={styles.divider}></div>

        <button className={styles.count} onClick={sendMessage}>
          Click
        </button>
        <div className={styles.divider}></div>
        <button className={styles.reset} onClick={() => updateSelf(0)}>
          Reset
        </button>
      </main>
    </div>
  );
};

export default Home;
