import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { supabase } from "../utils/supabase";

const channel = supabase.channel("user1-location", {
  configs: {
    broadcast: { ack: true },
  },
});

const Home: NextPage = () => {
  const [self, setSelf] = useState(0);
  const [openent, setOpenent] = useState(0);

  function subscribe() {
    channel
      .on("broadcast", { event: "location" }, (payload) =>
        setOpenent(payload.payload.count)
      )
      .subscribe((status: string) => {
        if (status == "SUBSCRIBED") {
          console.log("Connected");
        }
      });
  }

  async function sendMessage() {
    if (openent < 25 && self < 25) {
      const newCount = self + 1;
      setSelf(newCount);

      await channel.send({
        type: "broadcast",
        event: "location",
        payload: { count: newCount },
      });
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={subscribe}>Connect</button>
        <div className={styles.divider}>
          {`( Self: ${self} ) -----  ( Openent: ${openent} )`}
        </div>
        <button onClick={sendMessage}>Click</button>
      </main>
    </div>
  );
};

export default Home;
